spring:
  application:
    name: gateway-server-eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     # 通过 serviceId 转发到具体的服务实例，serviceId必须大写
      routes:
      - id: add_request_parameter_route
        uri: lb://eureka-producer
        filters:
        - AddRequestParameter=foo, bar
        predicates:
        - Method=GET

server:
  port: 8117

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
