spring:
  application:
    name: eureka-producer
  zipkin:
    base-url: http://localhost:8116   # zipkin 分布式链路跟踪
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8104

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
