spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xs19951018/springcloud-admin
          search-paths: springcloud-config/config-repo
          username: 1010665027@qq.com
          password: xs5412442

server:
  port: 8111

