spring:
  application:
    name: eureka-server

server:
  port: 8102

eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:8101/eureka/,http://peer1:8103/eureka/

