spring:
  application:
    name: eureka-server

server:
  port: 8103

eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:8101/eureka/,http://peer2:8102/eureka/

