spring:
  application:
    name: zipkin-server

server:
  port: 8116

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
    registry-fetch-interval-seconds: 7    # 客户端从服务端抓取服务间隔
