spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xs19951018/springcloud-admin
          search-paths: springcloud-config/config-repo
          username: 1010665027@qq.com
          password: xs5412442
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 8113

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/    # 注册中心eureka地址

management:
  security:
    enabled: false  # 刷新时，关闭安全验证
